### ISSUE TITLE
ERROR: Error: [dispatch] write: failed to generate C_SELECT_CHANNEL<1>:

### ISSUE THREAD

**Issue by mypka1551** [tsunpot/channel-switch-command#1]
I got this problem. What is wrong? Ty.

[12:36:42.460] [command] ERROR: Error: [dispatch] write: failed to generate C_SELECT_CHANNEL<1>:
Error: code not known for message "C_SELECT_CHANNEL"
    at Dispatch.write (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:330:23)
    at Module.toServer (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:165:30)
    at String.<anonymous> (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\channel-switch-command-master\index.js:19:10)
    at CommandBase.exec (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:443:45)
    at Socket.<anonymous> (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\clients\RealClient.js:38:45)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)

**Comment by tsunpot** [comment]
It looks like you're missing the opcode for it. Are you NA/EU?

**Comment by tsunpot** [comment]
C_SELECT_CHANNEL = 45788
if you're anywhere else, then you'll have to map it or have someone else map it for you

**Comment by mypka1551** [comment]
Can you tell me, which file i have to change? ty.

**Comment by tsunpot** [comment]
You need to add the line:

C_SELECT_CHANNEL = 45788

To protocol.353399.map which is located in your proxy folder > node modules > tera-data > protocol > protocol.353399.map

**Comment by mypka1551** [comment]
Thank you. It's working! :)
